---
title: "Virology (2024, Columbia Universtiy)"
---

Lectures of Vincent Racaniello

## Lecture 1

* Viruses are everywhere
* Viral genomes are a part of our own genetic material
* The numbers of viruses on Earth is staggering
* The vast majority of viruses that infect us have little to no impact on our health or wellbeing
  * Just passing through e.g. pepper mild mottle virus
  * Beneficial viruses
  * We have an amazing immune system
* Viruses shape host populations and vice-versa
* Virology is an integrative science
* Lots of people who don't know what they are talking about weigh in on virology -- hopefully not me in future!
* Definition: an infectious, obligate intracellular parasite comprising genetic material (DNA or RNA), surrounded by a protein coat, sometimes a membrane
* When we study viruses, we must also learn something about the host too
* Viruses have two phases: virion, infected cell
* ...are passive agents! Do not anthropomorphise
* ...are very small! (There are also "giant" viruses)
* ...replicate by assembly of pre-formed components into many particles
* Virus classification by nucleic acid
  * Kingdon, phylum, class, ...
* Barely sampling anything out there! Tonnes of viruses to discover
* Two key facts
  * All viral genomes are obligate molecular parasites that can only function after they replicate in a cell
  * All viruses must make mRNA that can be translated by host ribosomes
