---
title: "GNU make"
format: html
---

Notes on the ["GNU make manual"](https://www.gnu.org/software/make/manual/make.html).

## Overview

* Automatic determination of which parts of a large program need to be recompiled
* Works with any programming language whose compiler can be run with a shell command
  * Note: a shell is a general term for a program that provides an interface to interact with an operating system. There are many shells, including Bourne shell (sh), Bash (Bourne Again Shell), C Shell (csh), Korn Shell (ksh), Z shell (zsh), ...
  * Bash was developed by the GNU project, founded on the principles of free software
  * Unix is an operating system (OS) developed by AT&T's Bell Labs -- it serves as basis or inspiration for linux and macOS
* Uses the "makefile data base" and last-modification times of files to decide which files need to be updated

## Introduction

* A makefile consists of rules

```
target … : prerequisites …
        recipe
        …
        …
```

* `target` is usually the name of the file generated by the program
  * Could also be the name of an action to carry out ("phony target")
* `prerequisites` are files used as input to create the target
* `recipe` is an action that `make` carries out

## Writing Makefiles

* 